--- 
############################################################################################
# INITIAL SETUP                                                                            #
############################################################################################
- 
  become: true		      # Sudo all commands in the playbook
  hosts: all    		    # Defines what computers this is being run on
  name: service-acct    # Name of the playbook
# remote_user: techs    # Not defined here as it should be specified at playbook runtime by the user

############################################################################################
# RUNNING THE PLAY                                                                         #
############################################################################################  
  
  roles:
    - service-acct
