#################################################
#           CIDSE ANSIBLE PLAYBOOK              #
#################################################
#              MASTER PLAYBOOK                  #
#################################################

- name: cidse | common
  import_playbook: common.yml
  
- name: cidse | join-domain
  import_playbook: join-domain.yml

- name: cidse | landscape
  import_playbook: landscape.yml

