#################################################
#           CIDSE ANSIBLE PLAYBOOK              #
#################################################
#              MASTER PLAYBOOK                  #
#################################################



