---
############################################################################################
# DEFAULT VARIABLES FOR COMMON ROLE                                                        #
############################################################################################
common_packages:
  - byobu                 # Used for kernel cleanup cron job
  - cifs-utils
  - clamav-daemon
  - clamtk
  - curl
  - git
  - gksu
  - google-chrome-stable
  - grub2-splashimages
  - openssh-server
  - open-vm-tools
  - pbis-open
  - sublime-text

common_aptkeys:
  - https://download.sublimetext.com/sublimehq-pub.gpg
  - https://dl-ssl.google.com/linux/linux_signing_key.pub
  - http://repo.pbis.beyondtrust.com/apt/RPM-GPG-KEY-pbis

common_repos:
   - repo: https://download.sublimetext.com/
     add: apt/stable/
     file: sublime-text
   - repo: "[arch=amd64] http://dl.google.com/linux/chrome/deb/"
     add: stable main
     file: google-chrome
   - repo: http://repo.pbis.beyondtrust.com/apt/
     add: pbiso main
     file: pbiso

common_fsuser: "deploy"
common_fspass: "$6$E6FH6Lsg30j$uasCbR704g1n06T7br76L8g6dmDPrX49Rl2lXvaO3jZSn67gdmvHP5bykzsg9ugH7e1mxfW5wnHdN7Lx9Fi7z."