---

- name: Creating {{ cups_ppd_shared_location }}
  file:
    path: "{{ cups_ppd_shared_location }}"
    recurse: yes
    state: directory

- name: Install CUPS
  apt: name=cups state=latest
  
- name: Copy PPDs in the ppds_to_be_copied folder
  copy:
    src: "{{ role_dir }}/files/{{ item }}"
    dest: "{{ cups_ppd_shared_location }}"
    owner: root
    group: root
    mode: 0644
  when: cups_ppd_files_to_be_copied|default("") != ""
  with_items:
   - "{{ cups_ppd_files_to_be_copied }}"
   
- name: Enable the cups service
  service: name=cups enabled=yes

- name: Ensure cups is running
  service: name=cups state=started
  
- name: Make FSE Directory
  file:
    path: /var/log/fse/
    state: directory
    mode: 0755
    
- name: Map printers using lpadmin
  shell: "lpadmin -p {{ item.name }} -v socket://{{ item.socket }} -P {{ item.ppd }}"
  args: 
    creates: /var/log/fse/{{ item.name }}.installed
  with_items:
   - "{{ printer_list }}"

- name: Enable and accepting printer
  shell: "cupsenable {{ item.name }} && cupsaccept {{ item.name }}"
  args: 
    creates: /var/log/fse/{{ item.name }}.enabled
  with_items:
   - "{{ printer_list }}"