---
############################################################################################
# DEBIAN TASKS                                                                             #
############################################################################################

##########################################################################
# Create the service account                                             #
##########################################################################
- 
  user: 
    name: "{{ serviceacct_user }}"
    password: "{{ serviceacct_pass }}"
    groups: sudo
    update_password: always
    state: present
  name: "debian | provision CIDSE Ansible service account"