---
############################################################################################
# DEBIAN TASKS                                                                             #
############################################################################################

##########################################################################
# Create the service account                                             #
##########################################################################
- 
 user: 
   groups: sudo
   name: "{{ serviceacct_user }}"
   password: "{{ serviceacct_pass }}"
   state: present
   update_password: always
 name: "debian | provision CIDSE Ansible service account"