---
galaxy_info:
  author: Hitesh Prabhakar
  description: Installs CUPS, installs necessary PPDs and installs printers and classes on CUPS
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - stretch
        - jessie
        - wheezy
    - name: Ubuntu
      versions:
        - xenial
        - trusty
        - precise
  
  galaxy_tags:
    - cups
    - printing

dependencies: []
