---
############################################################################################
# DEBIAN TASKS                                                                             #
############################################################################################

##########################################################################
# Update root password                                                   #
##########################################################################
#- 
#  user: 
#    name: root
#    password: "{{ common_rtpass }}"
#    update_password: always
#  name: "debian | update root password"

##########################################################################
# Update Techs password                                                   #
##########################################################################
#- 
#  user: 
#    name: techs
#    password: "{{ common_techspass }}"
#    update_password: always
#  name: "debian | update techs password"

##########################################################################
# Enable serial communication over USB for all users                     #
##########################################################################
#
# This is used by the classes who plug Intel Galileo boards into the
# computers. BY default Linux requires users to have sudo to enable serial
# over USB. This writes a rule that is read on boot to allow all users to
# modify the TTY interfaces an enable serial communication. More info below
#
# https://askubuntu.com/questions/112568/how-do-i-allow-a-non-default-user-to-use-serial-device-ttyusb0
#
# Add the lines to the file
# lineinfile marked as preview as of writing, interface subject to change
-
  lineinfile:
    dest: /etc/udev/rules.d/50-myusb.rules
    state: present
    create: yes
    mode: 0644
    line: 'KERNEL=="ttyACM[0-9]*",MODE="0666"'
  name: debian | enable serial over USB for all users
  
##########################################################################
# Add apt keys and repositories                                          #
##########################################################################
-
 apt_key:
   state: present
   url: "{{ item }}"
 with_items:
   - "{{ common_aptkeys }}"
 name: debian | add common apt keys

- 
 apt_repository:
   repo: deb {{ item.repo }} {{ item.add }}
   state: present
   filename: "{{ item.file }}"
 with_items:
   - "{{ common_repos }}"
 name: debian | add common repositories

##########################################################################
# Update and upgrade packages (apt-get update && apt-get upgrade)        #
##########################################################################
- 
  apt: 
    cache_valid_time: 43200
    upgrade: dist
    autoremove: yes
  name: "debian | update and upgrade existing packages"

##########################################################################
# Install new packages as defined in 'my_packages' variable              #
##########################################################################
-
  apt:
    state: latest
    pkg: "{{ common_packages }}"
    cache_valid_time: 43200
  name: debian | install CIDSE common packages

##########################################################################
# Copy over end user wallpaper                                           #
##########################################################################
- 
  copy:
    src: "{{ role_path }}/files/warty-final-ubuntu.png"
    dest: "/usr/share/backgrounds/warty-final-ubuntu.png"
    owner: root
    group: root
    mode: 0744
    force: yes
  name: debian | copy end-user wallpaper
  
##########################################################################
# Setup purge old kernels cron job                                       #
##########################################################################
# Cron jobs run as root just FYI, hence no sudo
# This will keep the three most recent kernels (as safe measure)
# NOTE: cron module is marked as preview in Ansible 2.5 so interface for
# it could change and break in the future
# 
# This particular cron job will run every Monday at 00:30
-
  cron:
    minute: "30"
    weekday: "1"
    job: "purge-old-kernels --keep 3 -qy"
    state: present
    name: Weekly cleanup of old kernels
    cron_file: /etc/crontab
    user: root
  name: debian | purge old kernels cronjob setup
