---
ara_apt_packages: 
  - gcc 
  - python-dev
  - libffi-dev
  - libssl-dev
  - python-pip
  - libxml2-dev
  - libxslt1-dev

ara_pip_packages:
  - tox
  - ara 

ara_apache_packages:
  - apache2
  - libapache2-mod-wsgi